#!/bin/sh

for t in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15
do
	echo === Test $t ===
	sort -n < tests/$t > tests/$t.expected
	./useIntList < tests/$t > tests/$t.observed

	DIFF=$(diff tests/$t.expected tests/$t.observed)

	if [[ $DIFF != "" ]];
	then
		echo "  \033[0;31TEST FAILED\033[0m"
	else
		echo "  \033[0;32mTEST PASSED\033[0m"
	fi
done
rm tests/*.expected tests/*.observed
